#!/usr/bin/env bun
/**
 * Fetch en.ts and zh.ts from OpenCode repo, parse them,
 * and build an English-value → Chinese-value translation map.
 *
 * Output: src/translations/map.json
 */

const BASE = "https://raw.githubusercontent.com/anomalyco/opencode/dev/packages"
const FILES = [
  { url: `${BASE}/app/src/i18n/en.ts`, out: "en.ts" },
  { url: `${BASE}/app/src/i18n/zh.ts`, out: "zh.ts" },
  { url: `${BASE}/desktop/src/renderer/i18n/en.ts`, out: "desktop-en.ts" },
  { url: `${BASE}/desktop/src/renderer/i18n/zh.ts`, out: "desktop-zh.ts" },
]

const OUT_DIR = "src/translations"
const RAW_DIR = "scripts/raw"

async function fetchFile(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`)
  return await res.text()
}

/**
 * Parse a TypeScript dict file like:
 *   export const dict = {
 *     "key.name": "value",
 *     "another": 'value with {{param}}',
 *   }
 * Returns a Map<string, string>
 */
function parseDict(tsContent) {
  const dict = {}
  // Match "key": "value" or "key": 'value' patterns
  // Handle multi-line and single-line
  const lines = tsContent.split("\n")
  for (const line of lines) {
    // Match: "key.name": "value",  or  "key": 'value',
    // Also handle values with escaped quotes
    const match = line.match(/^\s*"([a-zA-Z0-9_.]+)":\s*"((?:[^"\\]|\\.)*)"\s*,?\s*$/)
    if (match) {
      const [, key, value] = match
      dict[key] = value.replace(/\\"/g, '"').replace(/\\n/g, '\n')
      continue
    }
    // Single-quoted values
    const match2 = line.match(/^\s*"([a-zA-Z0-9_.]+)":\s*'((?:[^'\\]|\\.)*)'\s*,?\s*$/)
    if (match2) {
      const [, key, value] = match2
      dict[key] = value.replace(/\\'/g, "'").replace(/\\n/g, '\n')
    }
  }
  return dict
}

async function main() {
  const { mkdirSync, writeFileSync, existsSync, readFileSync } = await import("node:fs")
  if (!existsSync(RAW_DIR)) mkdirSync(RAW_DIR, { recursive: true })
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })

  // Fetch all files
  const dicts = {}
  for (const { url, out } of FILES) {
    console.log(`Fetching ${url}...`)
    const content = await fetchFile(url)
    writeFileSync(`${RAW_DIR}/${out}`, content)
    const dict = parseDict(content)
    dicts[out] = dict
    console.log(`  Parsed ${Object.keys(dict).length} keys from ${out}`)
  }

  // Merge app + desktop dicts
  const enFull = { ...dicts["en.ts"], ...dicts["desktop-en.ts"] }
  const zhFull = { ...dicts["zh.ts"], ...dicts["desktop-zh.ts"] }

  console.log(`\nMerged EN keys: ${Object.keys(enFull).length}`)
  console.log(`Merged ZH keys: ${Object.keys(zhFull).length}`)

  // Find translated keys (zh has the key AND the value differs from en)
  let translated = 0
  let missing = 0
  const enToZh = {}  // English value → Chinese value
  const missingKeys = []  // Keys that need translation

  for (const [key, enValue] of Object.entries(enFull)) {
    const zhValue = zhFull[key]
    if (zhValue && zhValue !== enValue) {
      enToZh[enValue] = zhValue
      translated++
    } else {
      missingKeys.push({ key, enValue })
      missing++
    }
  }

  console.log(`\nTranslated: ${translated} (${(translated / (translated + missing) * 100).toFixed(1)}%)`)
  console.log(`Missing: ${missing} (${(missing / (translated + missing) * 100).toFixed(1)}%)`)

  // Merge supplement translations if they exist
  let supplement = {}
  try {
    const supContent = readFileSync(`${OUT_DIR}/supplement.json`, "utf-8")
    supplement = JSON.parse(supContent)
    console.log(`\nLoaded ${Object.keys(supplement).length} supplement translations`)
  } catch {
    console.log("\nNo supplement.json found (will be created manually)")
  }

  // Merge: supplement overrides enToZh
  const fullMap = { ...enToZh, ...supplement }

  // Generate TypeScript module with embedded data
  const tsContent = `// AUTO-GENERATED by scripts/build-map.ts — DO NOT EDIT
export const translationMap: Record<string, string> = ${JSON.stringify(fullMap, null, 2)}
`
  writeFileSync(`${OUT_DIR}/translations.ts`, tsContent)
  console.log(`Saved ${Object.keys(fullMap).length} translations to ${OUT_DIR}/translations.ts`)

  // Save missing keys for reference
  writeFileSync(`${OUT_DIR}/missing.json`, JSON.stringify(missingKeys, null, 2))
  console.log(`Saved ${missingKeys.length} missing keys to ${OUT_DIR}/missing.json`)
}

main().catch(console.error)
